//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalalimAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalalimEntities : DbContext
    {
        public MalalimEntities()
            : base("name=MalalimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivationUserInformation> ActivationUserInformations { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Intrest> Intrests { get; set; }
        public virtual DbSet<OrderCoupon> OrderCoupons { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<tbl_AdminRoles> tbl_AdminRoles { get; set; }
        public virtual DbSet<tbl_AdminUserClaims> tbl_AdminUserClaims { get; set; }
        public virtual DbSet<tbl_AdminUserLogins> tbl_AdminUserLogins { get; set; }
        public virtual DbSet<tbl_AdminUsers> tbl_AdminUsers { get; set; }
        public virtual DbSet<tbl_ClientRoles> tbl_ClientRoles { get; set; }
        public virtual DbSet<tbl_ClientUserClaims> tbl_ClientUserClaims { get; set; }
        public virtual DbSet<tbl_ClientUserLogins> tbl_ClientUserLogins { get; set; }
        public virtual DbSet<tbl_ClientUsers> tbl_ClientUsers { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<UserIntrest> UserIntrests { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
    }
}
